import type { FaqItem } from '@/app/ui/faq';

// Region-spezifische FAQ – liefert Content + FAQPage-Rich-Snippets pro Region.
export const FAQS_BY_REGION: Record<string, FaqItem[]> = {
  kaernten: [
    { q: 'Welcher ist der wärmste Badesee in Kärnten?', a: 'Der Klopeiner See in Südkärnten ist mit durchschnittlich 26–29 °C der wärmste Badesee Österreichs – durch das flache Becken und die geschützte Lage erwärmt er sich besonders schnell.' },
    { q: 'Wann ist die beste Reisezeit für Kärnten?', a: 'Juli und August sind am wärmsten, aber am vollsten. Geheimtipp ist der September: Die Seen haben noch 22–25 °C, die Preise fallen deutlich und die Strände sind leer. Für Wanderungen ist Juni ideal.' },
    { q: 'Gibt es kostenlose Badestellen am Wörthersee?', a: 'Ja, z. B. der Freistrand Maria Wörth und die Badebucht Reifnitz. Auch kleinere Seen wie der Keutschacher See bieten kostenlose Zugänge.' },
    { q: 'Welche Wanderung lohnt sich für Anfänger?', a: 'Die Seepromenade Klagenfurt–Pörtschach (flach) und der Nockberge-Höhenweg sind ideal für Einsteiger und Familien. Den Wegverlauf siehst du auf unserer interaktiven Karte.' },
    { q: 'Ist Kärnten auch im Winter einen Besuch wert?', a: 'Absolut: Der Weissensee wird zu Europas größter Natureisfläche, und Skigebiete wie Bad Kleinkirchheim (mit Therme) und das Nassfeld bieten über 100 km Pisten.' },
    { q: 'Wie viele Tage sollte man für Kärnten einplanen?', a: 'Für einen reinen See-Urlaub reichen vier bis fünf Tage, um zwei bis drei Seen und eine Wanderung unterzubringen. Wer zusätzlich Nockberge, Großglockner und Klagenfurt sehen will, sollte eher eine Woche einplanen.' },
    { q: 'Was kann man in Kärnten bei Regen machen?', a: 'Tropfsteinhöhlen und Schaubergwerke sind wetterunabhängig, dazu kommen Burg Hochosterwitz, Minimundus in Klagenfurt und die Thermen. Eine sortierte Übersicht findest du auf unserer Seite zu regentauglichen Ausflügen.' },
    { q: 'Braucht man in Kärnten ein Auto?', a: 'Für die großen Seen nicht zwingend: Klagenfurt, Villach, Velden und Pörtschach sind per Bahn erreichbar, dazu gibt es Schifffahrt und gut ausgebaute Radwege. Für Nockberge, Großglockner und abgelegenere Badeplätze ist ein Auto aber deutlich praktischer.' },
    { q: 'Sind Hunde an Kärntens Seen erlaubt?', a: 'Das ist von Bad zu Bad verschieden. Viele Strandbäder lassen keine Hunde ins Wasser, es gibt aber ausgewiesene Hundestrände und frei zugängliche Uferstellen. Am besten vorab beim jeweiligen Bad nachfragen.' },
  ],
  salzburg: [
    { q: 'Was muss man in Salzburg gesehen haben?', a: 'Die UNESCO-Altstadt mit Getreidegasse, die Festung Hohensalzburg, Mozarts Geburtshaus und den Mirabellgarten. Im Umland lohnen Zell am See, die Krimmler Wasserfälle und die Eisriesenwelt.' },
    { q: 'Welcher See in Salzburg ist zum Baden am besten?', a: 'Der Zeller See bietet Baden mit Bergpanorama. Im Salzburger Seenland (Wallersee, Mattsee, Obertrumer See) findest du warme, ruhigere Badeseen nur 20–40 Minuten von der Stadt.' },
    { q: 'Lohnt sich die Salzburg Card?', a: 'Wenn du mehrere Sehenswürdigkeiten besuchst: ja. Sie umfasst freien Eintritt zu Museen und Attraktionen sowie die öffentlichen Verkehrsmittel und die Festungsbahn.' },
    { q: 'Beste Reisezeit für Salzburg?', a: 'Die Stadt ist ganzjährig schön (im Advent besonders stimmungsvoll). Für Badeseen und Bergwanderungen sind Juni bis September ideal.' },
    { q: 'Wie viele Tage braucht man für Salzburg?', a: 'Für die Altstadt reichen zwei Tage. Mit Ausflügen ins Salzkammergut, zu den Krimmler Wasserfällen oder auf die Großglockner-Hochalpenstraße werden daraus schnell fünf bis sieben Tage.' },
    { q: 'Was kann man in Salzburg bei Regen machen?', a: 'Die Eisriesenwelt und die Salzwelten am Dürrnberg liegen im Berg, dazu Festung Hohensalzburg, die Museen der Altstadt und Schloss Hellbrunn. In der Stadt ist fast alles zu Fuß und weitgehend im Trockenen erreichbar.' },
    { q: 'Ist Salzburg ohne Auto machbar?', a: 'In der Stadt und im näheren Umland ja: Die Altstadt erkundet man zu Fuß, Bus und Bahn decken das Seenland und das Salzkammergut ab. Für Hohe Tauern, Krimml und die Hochalpenstraße ist ein Auto oder eine organisierte Tour praktischer.' },
    { q: 'Wann ist die Großglockner-Hochalpenstraße befahrbar?', a: 'Sie ist eine reine Sommerstraße und je nach Schneelage etwa von Anfang Mai bis Ende Oktober offen. Die Straße ist mautpflichtig – Öffnungszeitraum und Tarife vor der Fahrt beim Betreiber prüfen.' },
  ],
  tirol: [
    { q: 'Was sind die Top-Sehenswürdigkeiten in Tirol?', a: 'Innsbruck mit Goldenem Dachl und Nordkette, der Achensee, das Ötztal mit Sölden, das Zillertal sowie die Swarovski Kristallwelten bei Wattens.' },
    { q: 'Welcher See in Tirol ist zum Baden geeignet?', a: 'Der Achensee ist Tirols größter See – klar und top zum Segeln und Surfen. Ruhiger und ein Geheimtipp ist der Plansee im Westen Tirols.' },
    { q: 'Kann man in Tirol auch im Sommer Ski fahren?', a: 'Ja, am Hintertuxer Gletscher (ganzjährig) sowie saisonal am Stubaier und Sölden-Gletscher liegt auch im Sommer Schnee.' },
    { q: 'Beste Reisezeit für Tirol?', a: 'Zum Wandern und Baden Juni–Oktober, zum Skifahren Dezember–April. Innsbruck und die Gletscher lohnen ganzjährig.' },
    { q: 'Wie viele Tage sollte man für Tirol einplanen?', a: 'Ein einzelnes Tal lässt sich in drei bis vier Tagen gut erleben. Wer Innsbruck mit mehreren Tälern und einem Gletscher verbinden will, plant besser eine Woche – die Fahrzeiten zwischen den Tälern werden regelmäßig unterschätzt.' },
    { q: 'Was kann man in Tirol bei Regen machen?', a: 'Die Swarovski Kristallwelten, die Festung Kufstein und die Museen in Innsbruck funktionieren bei jedem Wetter. Dazu gibt es in fast jedem größeren Tal ein Erlebnisbad oder eine Therme.' },
    { q: 'Ist Tirol gut mit Öffis erreichbar?', a: 'Die Haupttäler sind per Bahn sehr gut erschlossen, und in vielen Regionen bringen Wanderbusse Gäste zu den Ausgangspunkten. Häufig ist mit der Gästekarte der Unterkunft ein Teil davon enthalten – Konditionen beim Quartier erfragen.' },
    { q: 'Welche Region in Tirol eignet sich für Familien?', a: 'Das Alpbachtal, der Kaiserwinkl rund um den Walchsee und weite Teile des Zillertals sind auf Familien ausgerichtet: moderate Wege, viele Bergbahnen und Badeseen in der Nähe.' },
  ],
  steiermark: [
    { q: 'Was sind die Highlights der Steiermark?', a: 'Graz mit seiner UNESCO-Altstadt, der Dachstein mit Skywalk, der Grüne See in Tragöß, die Südsteirische Weinstraße und der Nationalpark Gesäuse.' },
    { q: 'Wann ist der Grüne See am schönsten?', a: 'Im Mai und Juni: Dann lässt die Schneeschmelze den See auf den höchsten Stand steigen und das Wasser leuchtet besonders smaragdgrün. Tauchen und Schwimmen sind dort verboten.' },
    { q: 'Was ist typisch steirisch?', a: 'Kürbiskernöl („grünes Gold"), Sauvignon Blanc von der Weinstraße, Käferbohnen und die Zotter-Schokolade. Die Oststeiermark ist als Genussregion bekannt.' },
    { q: 'Beste Reisezeit für die Steiermark?', a: 'Mai bis Oktober. Für die Weinstraße ist der Herbst (Weinlese) besonders stimmungsvoll, für den Grünen See der Frühsommer.' },
    { q: 'Wie viele Tage sollte man für die Steiermark einplanen?', a: 'Graz allein füllt zwei Tage. Für die Kombination aus Stadt, Weinstraße und Bergen (Dachstein oder Gesäuse) sind fünf bis sieben Tage realistisch – die Steiermark ist größer, als viele denken.' },
    { q: 'Was kann man in der Steiermark bei Regen machen?', a: 'Die Lurgrotte als größte Tropfsteinhöhle Österreichs, das Schaubergwerk am Erzberg, Stift Admont mit seiner Klosterbibliothek sowie die Grazer Museen und die Thermen der Oststeiermark.' },
    { q: 'Welche Thermen gibt es in der Steiermark?', a: 'Die Oststeiermark ist als Thermenland bekannt – unter anderem mit Loipersdorf und dem von Hundertwasser gestalteten Rogner Bad Blumau. Angebot und Öffnungszeiten unterscheiden sich stark, ein Blick auf die Betreiberseite lohnt.' },
    { q: 'Ist die Südsteirische Weinstraße mit dem Rad machbar?', a: 'Ja, aber es ist hügeliger, als es auf Fotos wirkt: Die Weinstraße führt über zahlreiche Kuppen. Mit einem E-Bike wird es deutlich entspannter, sonst sollte man Kondition mitbringen.' },
  ],
  burgenland: [
    { q: 'Was macht den Neusiedler See besonders?', a: 'Er ist Mitteleuropas größter Steppensee – sehr flach (meist ~1 m), dadurch warm und ideal für Kinder, und durch den verlässlichen Wind top zum Segeln und Surfen. Der Schilfgürtel ist UNESCO-Welterbe.' },
    { q: 'Wann sieht man die Störche in Rust?', a: 'Von April bis etwa August nisten die Störche auf den Kaminen der Altstadt von Rust – am schönsten in den Sommermonaten.' },
    { q: 'Wofür ist das Burgenland bekannt?', a: 'Für Spitzenweine (Blaufränkisch, edelsüße Weine), das pannonische Sonnenklima, den Neusiedler See und Thermen wie Lutzmannsburg.' },
    { q: 'Beste Reisezeit für das Burgenland?', a: 'Mai bis September für See und Wein, der November für das traditionelle Martiniloben mit Gansl und Jungwein.' },
    { q: 'Wie viele Tage sollte man für das Burgenland einplanen?', a: 'Drei bis vier Tage reichen für den Neusiedler See mit Rust, Podersdorf und einer Radrunde. Wer auch das Südburgenland mit Burgen und Uhudler sehen will, plant besser fünf bis sechs Tage.' },
    { q: 'Was kann man im Burgenland bei Regen machen?', a: 'Die Thermen sind der naheliegende Plan B, dazu Schloss Esterházy in Eisenstadt, Burg Forchtenstein und die Weingüter mit Verkostung. Das flache Land bietet wenig natürlichen Schutz – Innenprogramm lohnt sich hier besonders.' },
    { q: 'Ist der Neusiedler See für kleine Kinder geeignet?', a: 'Ja, das ist eine seiner größten Stärken: Das Wasser ist über weite Strecken sehr flach und wird im Sommer warm. Auf Wind und Sonnenschutz sollte man trotzdem achten – Schatten ist am offenen See rar.' },
    { q: 'Lohnt sich der Neusiedler See Radweg?', a: 'Sehr – die Runde um den See ist flach, durchgehend beschildert und lässt sich durch Fährverbindungen abkürzen. Der Wind ist der eigentliche Gegner, nicht die Steigung: Fahrtrichtung nach Windrichtung wählen.' },
  ],
  wien: [
    { q: 'Was muss man in Wien gesehen haben?', a: 'Schloss Schönbrunn, den Stephansdom und die Altstadt, den Prater mit Riesenrad sowie ein klassisches Kaffeehaus. Im Sommer lohnt zusätzlich ein Bad an der Alten Donau.' },
    { q: 'Wo kann man in Wien baden?', a: 'An der Alten Donau (ruhig, ideal für Familien), auf der Donauinsel (kostenlos, lange Ufer) und im Gänsehäufel-Strandbad. Mitten in der Stadt und gut mit Öffis erreichbar.' },
    { q: 'Wie bewegt man sich in Wien am besten fort?', a: 'Mit den Öffis: U-Bahn, Straßenbahn und Bus decken alles ab. Die Innenstadt erkundet man am besten zu Fuß, ein Auto braucht man nicht.' },
    { q: 'Wann ist die beste Reisezeit für Wien?', a: 'Mai/Juni und September für mildes Wetter und blühende Gärten. Der Advent mit den Christkindlmärkten ist besonders stimmungsvoll.' },
    { q: 'Wie viele Tage sollte man für Wien einplanen?', a: 'Drei Tage reichen für die wichtigsten Sehenswürdigkeiten. Wer auch Museen in Ruhe besuchen, in den Wienerwald hinausfahren und Kaffeehauskultur wirklich erleben will, ist mit vier bis fünf Tagen besser bedient.' },
    { q: 'Was kann man in Wien bei Regen machen?', a: 'Wien ist eine der besten Schlechtwetter-Städte überhaupt: Museen, Schönbrunn mit Prunkräumen, der Stephansdom samt Katakomben und unzählige Kaffeehäuser. Fast alles ist mit der U-Bahn ohne langen Fußweg erreichbar.' },
    { q: 'Kann man von Wien aus gut Tagesausflüge machen?', a: 'Ja, und zwar ohne Auto: Wachau, Neusiedler See, Schneeberg und Rax sind alle per Bahn erreichbar. Unsere Wochenendtrip-Seite ab Wien bündelt die Ziele nach Fahrzeit.' },
    { q: 'Wo wandert man in Wien?', a: 'Im Wienerwald direkt an der Stadtgrenze – über Kahlenberg und Leopoldsberg mit Blick über die Stadt. Die städtischen Stadtwanderwege sind ausgeschildert und alle mit Öffis erreichbar.' },
  ],
  oberoesterreich: [
    { q: 'Was ist im Salzkammergut ein Muss?', a: 'Hallstatt mit Salzwelten und Skywalk, der Traunsee bei Gmunden, der Attersee zum Baden und der Dachstein-Krippenstein mit der 5fingers-Plattform.' },
    { q: 'Welcher See ist zum Baden am besten?', a: 'Der Attersee und der Mondsee sind glasklar; der Mondsee wird etwas wärmer. Der Traunsee ist tief und kühl, dafür spektakulär vor dem Traunstein.' },
    { q: 'Ist Hallstatt zu überlaufen?', a: 'Tagsüber ja, vor allem mittags. Früh morgens oder am Abend wird es ruhiger – wer übernachtet, hat den Ort fast für sich.' },
    { q: 'Beste Reisezeit für Oberösterreich?', a: 'Juni bis September zum Baden und für Schifffahrten, der Herbst für ruhiges Wandern mit Nebelstimmung über den Seen.' },
    { q: 'Wie viele Tage sollte man für das Salzkammergut einplanen?', a: 'Vier bis fünf Tage, um zwei bis drei Seen, Hallstatt und den Krippenstein ohne Hetze zu verbinden. Hallstatt und Krippenstein an einem Tag zusammenzulegen, geht sich erfahrungsgemäß nicht entspannt aus.' },
    { q: 'Was kann man in Oberösterreich bei Regen machen?', a: 'Linz punktet mit Ars Electronica Center und Lentos, dazu kommen die Salzwelten in Hallstatt, die Dachstein-Höhlen und die Keramikmanufaktur in Gmunden. Höhlen sind wetterunabhängig, aber dauerhaft kalt.' },
    { q: 'Ist das Salzkammergut ohne Auto machbar?', a: 'Weitgehend ja: Bahn, Postbusse und Schifffahrt erschließen die Seen gut, Hallstatt erreicht man klassisch per Bahn und Fähre. In der Nebensaison sind die Takte allerdings dünner – Verbindungen vorher prüfen.' },
    { q: 'Wird Linz unterschätzt?', a: 'Ziemlich. Die Stadt hat den Ruf als Industriestandort längst hinter sich gelassen und ist heute UNESCO City of Media Arts – mit dem Ars Electronica Center, dem Lentos und einem der größten Stadtplätze Europas.' },
  ],
  niederoesterreich: [
    { q: 'Was muss man in der Wachau sehen?', a: 'Stift Melk, das mittelalterliche Dürnstein mit Burgruine, die Weinterrassen entlang der Donau und eine Donauschifffahrt zwischen Melk und Krems.' },
    { q: 'Rax oder Schneeberg – welcher Hausberg?', a: 'Beide sind bequem per Bahn erreichbar: die Rax mit der Seilbahn, der Schneeberg mit der Salamander-Zahnradbahn. Die Rax bietet ein sanftes, grünes Hochplateau und ist familienfreundlicher; der Schneeberg ist höher, karger und alpiner.' },
    { q: 'Wann blüht die Marille in der Wachau?', a: 'Meist Ende März bis Anfang April. Dann verwandeln die blühenden Marillenbäume das Donautal in ein Blütenmeer.' },
    { q: 'Kann man in Niederösterreich baden?', a: 'Ja, etwa im Lunzer See (wärmster Gebirgssee), im Erlaufsee oder im Stausee Ottenstein im Waldviertel.' },
    { q: 'Wie viele Tage sollte man für die Wachau einplanen?', a: 'Ein Tag reicht für Melk und Dürnstein im Schnelldurchlauf, ist aber sportlich. Mit zwei bis drei Tagen lassen sich Stift, Schifffahrt, eine Radetappe und ein Heurigenbesuch entspannt verbinden.' },
    { q: 'Was kann man in Niederösterreich bei Regen machen?', a: 'Stift Melk und Schloss Grafenegg bieten Kultur im Trockenen, dazu kommen die Museen in Krems und St. Pölten. Der Schneeberg und die Rax sind bei Schlechtwetter dagegen kein Ziel – oben ist es dann nass, kalt und ohne Sicht.' },
    { q: 'Ist die Wachau ohne Auto machbar?', a: 'Sehr gut sogar: Bahn bis Krems oder Melk, dann Schiff, Wachaubahn oder Leihrad. Gerade bei einer Weinverkostung ist die autofreie Variante die vernünftigere.' },
    { q: 'Was lohnt sich im Waldviertel?', a: 'Ruhige Wälder, Granitlandschaften, Stauseen zum Baden und Orte wie Zwettl oder Gmünd. Das Waldviertel ist deutlich weniger besucht als die Wachau – gut für alle, die Trubel vermeiden wollen.' },
  ],
  vorarlberg: [
    { q: 'Kann man im Bodensee baden?', a: 'Ja, in Bregenz und Lochau gibt es Strandbäder mit Liegewiesen. Im Hochsommer wird der See angenehm warm – dazu Alpenblick inklusive.' },
    { q: 'Was sind die Bregenzer Festspiele?', a: 'Ein berühmtes Opernfestival auf der größten Seebühne der Welt direkt am Bodensee, jeweils im Juli und August. Die Inszenierung auf dem See wird üblicherweise zwei Sommer hintereinander gespielt.' },
    { q: 'Wie kommt man zum Lünersee?', a: 'Mit der Lünerseebahn vom Brandnertal hinauf; oben führt ein leichter Rundweg um den türkisen Bergsee vor der Rätikon-Kulisse. Die Bahn hat saisonale Betriebszeiten.' },
    { q: 'Beste Reisezeit für Vorarlberg?', a: 'Juni bis September zum Baden, Wandern und für die Festspiele; der Winter zum Skifahren am Arlberg und im Montafon.' },
    { q: 'Wie viele Tage sollte man für Vorarlberg einplanen?', a: 'Vorarlberg ist kompakt: In vier bis fünf Tagen lassen sich Bodensee, Bregenzerwald und ein Bergtal wie das Brandnertal oder Montafon gut verbinden. Die Wege zwischen den Regionen sind kurz.' },
    { q: 'Was kann man in Vorarlberg bei Regen machen?', a: 'Das Kunsthaus Bregenz, der Werkraum im Bregenzerwald und die Sennereien entlang der KäseStrasse funktionieren bei jedem Wetter. Dazu laden die Museen und Bäder in Bregenz und Dornbirn ein.' },
    { q: 'Wofür ist der Bregenzerwald bekannt?', a: 'Für zwei Dinge, die selten zusammen auftreten: preisgekrönte moderne Holzarchitektur und traditionelle Sennereiwirtschaft mit Bergkäse. Die KäseStrasse verbindet Betriebe, Almen und Gasthäuser der Region.' },
    { q: 'Ist Vorarlberg mit Öffis gut erschlossen?', a: 'Ja, der Landbus deckt die Täler dicht ab und ist mit der Bahn im Rheintal verknüpft – ein Auto ist meist verzichtbar. Bei vielen Unterkünften ist eine Gästekarte für Bus und teils Bergbahnen dabei; Konditionen beim Quartier erfragen.' },
  ],
};
