// GENERIERT – nicht von Hand pflegen, sondern neu erzeugen.
//
// Echte Ortsfotos zu den Artikeln, bezogen von Wikimedia Commons.
//
// Auswahlverfahren (bewusst konservativ – lieber kein Bild als ein falsches):
//  1. Commons nach Dateien im Umkreis des Artikel-Startpunkts durchsuchen
//     (`list=geosearch`). Damit ist der Aufnahmeort objektiv belegt statt
//     per Wortsuche geraten – frühere Versuche über die Volltextsuche
//     lieferten ein Filmfestival-Portrait für „Karren“ und ein sächsisches
//     Schneeberg statt des niederösterreichischen.
//  2. Nur Lizenzen, die kommerzielle Nutzung erlauben (CC BY, CC BY-SA,
//     CC0, Public Domain). Die Seite finanziert sich über Werbung und
//     Affiliate-Links, „nicht-kommerziell“ wäre also unzulässig.
//  3. Nur Querformat ab 1400 px, Seitenverhältnis 1,3–2,6.
//  4. Der Dateiname muss Ortsname UND ein Landschafts- oder Bauwerksmotiv
//     nennen; Aufnahmeort höchstens 3,6 km vom Startpunkt entfernt.
//  5. Motive, die als Artikelkopf nichts taugen (Innenräume, Denkmäler,
//     Verkehrsbauten, Ortsschilder, Bankfilialen), fallen raus.
//  6. Abschließende Sichtung von Hand.
//
// Die Artikel ohne geprüftes Foto behalten das generierte Markenmotiv
// (`post-artwork.tsx`) – das ist ehrlicher als ein Bild, das den Ort
// nicht zeigt.
//
// `km` = gemessene Entfernung des Aufnahmeorts zum Startpunkt des Artikels.
// Namensnennung sichtbar am Artikelkopf und gesammelt unter /bildnachweis.

export type PostBild = {
  url: string;
  /** Breite geteilt durch Höhe – für das Seitenverhältnis der Bildfläche. */
  verhaeltnis: number;
  alt: string;
  autor: string;
  lizenz: string;
  quelle: string;
  km: number;
};

export const POST_BILDER: Record<string, PostBild> = {
  'achensee-tirol': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/South_view_of_Achensee_and_Pertisau_from_observation_platform_20231105_1.jpg/1920px-South_view_of_Achensee_and_Pertisau_from_observation_platform_20231105_1.jpg',
    verhaeltnis: 1.500,
    alt: 'Achensee',
    autor: 'DXR',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ASouth_view_of_Achensee_and_Pertisau_from_observation_platform_20231105_1.jpg',
    km: 1.71,
  },
  'almsee-gruenau-almtal': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Almsee_Herbst_2007_-_panoramio.jpg/1920px-Almsee_Herbst_2007_-_panoramio.jpg',
    verhaeltnis: 1.810,
    alt: 'Almsee im Almtal',
    autor: 'holger mohaupt',
    lizenz: 'CC BY-SA 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AAlmsee_Herbst_2007_-_panoramio.jpg',
    km: 2.32,
  },
  'altausseer-see-baden': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Altausseer_See_and_Trisselwand_%2846978265722%29.jpg/1920px-Altausseer_See_and_Trisselwand_%2846978265722%29.jpg',
    verhaeltnis: 1.500,
    alt: 'Altausseer See',
    autor: 'Bernd Thaller from Graz, Austria',
    lizenz: 'CC BY 2.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AAltausseer_See_and_Trisselwand_%2846978265722%29.jpg',
    km: 0.68,
  },
  'alte-donau-baden-wien': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/2017-06-11_AT_Wien_22_Donaustadt%2C_Obere_Alte_Donau%2C_Kagraner_Br%C3%BCcke_%2850342776077%29.jpg/1920px-2017-06-11_AT_Wien_22_Donaustadt%2C_Obere_Alte_Donau%2C_Kagraner_Br%C3%BCcke_%2850342776077%29.jpg',
    verhaeltnis: 1.501,
    alt: 'Alte Donau',
    autor: 'Paul Korecky',
    lizenz: 'CC BY-SA 2.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3A2017-06-11_AT_Wien_22_Donaustadt%2C_Obere_Alte_Donau%2C_Kagraner_Br%C3%BCcke_%2850342776077%29.jpg',
    km: 0.16,
  },
  'attersee-baden': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Aufham_27_south_of_Attersee_am_Attersee_seen_from_Attersee_in_Upper_Austria%2C_Austria_PNr%C2%B00878.jpg/1920px-Aufham_27_south_of_Attersee_am_Attersee_seen_from_Attersee_in_Upper_Austria%2C_Austria_PNr%C2%B00878.jpg',
    verhaeltnis: 1.626,
    alt: 'attersee-baden',
    autor: 'D-Kuru',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AAufham_27_south_of_Attersee_am_Attersee_seen_from_Attersee_in_Upper_Austria%2C_Austria_PNr%C2%B00878.jpg',
    km: 1.43,
  },
  'beste-badestellen-woerthersee': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Ufer_des_W%C3%B6rthersee_an_der_Halbinsel_in_P%C3%B6rtschach.jpg/1920px-Ufer_des_W%C3%B6rthersee_an_der_Halbinsel_in_P%C3%B6rtschach.jpg',
    verhaeltnis: 1.500,
    alt: 'schönsten Badestellen am Wörthersee',
    autor: 'Liberaler Humanist',
    lizenz: 'CC BY-SA 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AUfer_des_W%C3%B6rthersee_an_der_Halbinsel_in_P%C3%B6rtschach.jpg',
    km: 1.09,
  },
  'bludenz-alpenstadt-fuenf-taeler': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Bludenz_Laurentiuskirche_Schloss_Luftbild.jpg/1920px-Bludenz_Laurentiuskirche_Schloss_Luftbild.jpg',
    verhaeltnis: 1.621,
    alt: 'Bludenz',
    autor: 'Herbert Heim',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ABludenz_Laurentiuskirche_Schloss_Luftbild.jpg',
    km: 0.31,
  },
  'bregenzer-festspiele-seebuehne': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/2024194224126_2024-07-12_Bregenzer_Festspiele_-_Der_Freisch%C3%BCtz_-_Sven_-_1D_X_MK_II_-_1512_-_B70I1048.jpg/1920px-2024194224126_2024-07-12_Bregenzer_Festspiele_-_Der_Freisch%C3%BCtz_-_Sven_-_1D_X_MK_II_-_1512_-_B70I1048.jpg',
    verhaeltnis: 1.500,
    alt: 'Bregenzer Festspiele',
    autor: 'Sven Mandel',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3A2024194224126_2024-07-12_Bregenzer_Festspiele_-_Der_Freisch%C3%BCtz_-_Sven_-_1D_X_MK_II_-_1512_-_B70I1048.jpg',
    km: 0.04,
  },
  'burg-bernstein-edelserpentin': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Bernstein_-_Burg%2C_%C3%A4u%C3%9Ferer_Burghof.JPG/1920px-Bernstein_-_Burg%2C_%C3%A4u%C3%9Ferer_Burghof.JPG',
    verhaeltnis: 1.656,
    alt: 'Bernstein',
    autor: 'C.Stadler/Bwag',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ABernstein_-_Burg%2C_%C3%A4u%C3%9Ferer_Burghof.JPG',
    km: 0.26,
  },
  'burg-forchtenstein-ausflug': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Burg_Forchtenstein_05.jpg/1920px-Burg_Forchtenstein_05.jpg',
    verhaeltnis: 1.501,
    alt: 'Burg Forchtenstein',
    autor: 'Helmlechner',
    lizenz: 'CC0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ABurg_Forchtenstein_05.jpg',
    km: 0.04,
  },
  'burg-guessing-suedburgenland': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Burg-guessing-pano.jpg/1920px-Burg-guessing-pano.jpg',
    verhaeltnis: 1.586,
    alt: 'Burg Güssing',
    autor: 'Thomas Steiner',
    lizenz: 'CC BY-SA 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ABurg-guessing-pano.jpg',
    km: 0.34,
  },
  'burg-hochosterwitz-ausflug': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Burg_Hochosterwitz_Nordseite_01.jpg/1920px-Burg_Hochosterwitz_Nordseite_01.jpg',
    verhaeltnis: 1.500,
    alt: 'Burg Hochosterwitz',
    autor: 'Uoaei1',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ABurg_Hochosterwitz_Nordseite_01.jpg',
    km: 0.59,
  },
  'burg-lockenhaus': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Lockenhaus_-_Burg_%281%29.JPG/1920px-Lockenhaus_-_Burg_%281%29.JPG',
    verhaeltnis: 1.766,
    alt: 'Burg Lockenhaus',
    autor: 'C.Stadler/Bwag',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ALockenhaus_-_Burg_%281%29.JPG',
    km: 0.08,
  },
  'carnuntum-archaeologiepark': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Aerial_image_of_Carnuntum_%28view_from_the_southeast%29.jpg/1920px-Aerial_image_of_Carnuntum_%28view_from_the_southeast%29.jpg',
    verhaeltnis: 1.693,
    alt: 'Carnuntum',
    autor: 'Carsten Steger',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AAerial_image_of_Carnuntum_%28view_from_the_southeast%29.jpg',
    km: 0.72,
  },
  'dachstein-gletscher-skywalk': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Hoher_Dachstein_%282.995m%29_and_Niederer_Dachstein_%282.995m%29_with_Hallstatt_Gletscher.jpg/1920px-Hoher_Dachstein_%282.995m%29_and_Niederer_Dachstein_%282.995m%29_with_Hallstatt_Gletscher.jpg',
    verhaeltnis: 1.333,
    alt: 'Dachstein Gletscher & Sky Walk',
    autor: 'Stefan Kasberger',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AHoher_Dachstein_%282.995m%29_and_Niederer_Dachstein_%282.995m%29_with_Hallstatt_Gletscher.jpg',
    km: 0.24,
  },
  'dachstein-krippenstein': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Tiefblicke_auf_den_Hallst%C3%A4tter_See.jpg/1920px-Tiefblicke_auf_den_Hallst%C3%A4tter_See.jpg',
    verhaeltnis: 1.780,
    alt: 'Dachstein-Krippenstein',
    autor: 'Pallerti',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ATiefblicke_auf_den_Hallst%C3%A4tter_See.jpg',
    km: 0.16,
  },
  'die-10-besten-wanderwege-am-woerthersee': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Poertschach_Halbinselpromenade_Woerthersee-Blick_Richtung_Unterdellach_08032017_6496.jpg/1920px-Poertschach_Halbinselpromenade_Woerthersee-Blick_Richtung_Unterdellach_08032017_6496.jpg',
    verhaeltnis: 1.498,
    alt: '10 besten Wanderwege am Wörthersee',
    autor: 'Johann Jaritz',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3APoertschach_Halbinselpromenade_Woerthersee-Blick_Richtung_Unterdellach_08032017_6496.jpg',
    km: 1.03,
  },
  'donauinsel-wien': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/2017-06-18_AT_Wien_22_Donaustadt%2C_Ernst-Sadil-Platz%2C_G%C3%A4nseh%C3%A4ufelbr%C3%BCcke_%2850103642186%29.jpg/1920px-2017-06-18_AT_Wien_22_Donaustadt%2C_Ernst-Sadil-Platz%2C_G%C3%A4nseh%C3%A4ufelbr%C3%BCcke_%2850103642186%29.jpg',
    verhaeltnis: 1.500,
    alt: 'Donauinsel',
    autor: 'Paul Korecky',
    lizenz: 'CC BY-SA 2.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3A2017-06-18_AT_Wien_22_Donaustadt%2C_Ernst-Sadil-Platz%2C_G%C3%A4nseh%C3%A4ufelbr%C3%BCcke_%2850103642186%29.jpg',
    km: 0.18,
  },
  'eisriesenwelt-werfen': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Entrance_of_Eisriesenwelt_ice_cave_Werfen_Austria.jpg/1920px-Entrance_of_Eisriesenwelt_ice_cave_Werfen_Austria.jpg',
    verhaeltnis: 1.500,
    alt: 'Eisriesenwelt Werfen',
    autor: 'Lianguanlun',
    lizenz: 'CC BY 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AEntrance_of_Eisriesenwelt_ice_cave_Werfen_Austria.jpg',
    km: 0.82,
  },
  'familypark-st-margarethen': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Sankt_Margarethen_im_Burgenland%2C_Blick_zum_Nordteil_der_Gemeinde.jpg/1920px-Sankt_Margarethen_im_Burgenland%2C_Blick_zum_Nordteil_der_Gemeinde.jpg',
    verhaeltnis: 1.500,
    alt: 'Familypark St. Margarethen',
    autor: 'Dguendel',
    lizenz: 'CC BY 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ASankt_Margarethen_im_Burgenland%2C_Blick_zum_Nordteil_der_Gemeinde.jpg',
    km: 1.65,
  },
  'feldkirch-altstadt-schattenburg': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Feldkirch_Marktplatz_Weihnachtsbaum_Nacht.jpg/1920px-Feldkirch_Marktplatz_Weihnachtsbaum_Nacht.jpg',
    verhaeltnis: 1.752,
    alt: 'Feldkirch',
    autor: 'Herbert Heim',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AFeldkirch_Marktplatz_Weihnachtsbaum_Nacht.jpg',
    km: 0.14,
  },
  'filzmoos-bischofsmuetze': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/View_of_Filzmoos_%28Salzburg%29_29.jpg/1920px-View_of_Filzmoos_%28Salzburg%29_29.jpg',
    verhaeltnis: 1.333,
    alt: 'Filzmoos & Bischofsmütze',
    autor: 'Cherubino',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AView_of_Filzmoos_%28Salzburg%29_29.jpg',
    km: 0.6,
  },
  'freistadt-muehlviertel-altstadt': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Freistadt-2016-07-02-Hauptplatz-Bild01.jpg/1920px-Freistadt-2016-07-02-Hauptplatz-Bild01.jpg',
    verhaeltnis: 1.333,
    alt: 'Freistadt im Mühlviertel',
    autor: 'Miloš Hlávka',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AFreistadt-2016-07-02-Hauptplatz-Bild01.jpg',
    km: 0.03,
  },
  'fuschlsee-baden': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Fuschlsee_as_seen_from_Bauernhof_Unterh%C3%B6fner_01.jpg/1920px-Fuschlsee_as_seen_from_Bauernhof_Unterh%C3%B6fner_01.jpg',
    verhaeltnis: 1.776,
    alt: 'Fuschlsee',
    autor: 'Renek78',
    lizenz: 'CC0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AFuschlsee_as_seen_from_Bauernhof_Unterh%C3%B6fner_01.jpg',
    km: 1.32,
  },
  'geschriebenstein-wandern-burgenland': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Geschriebenstein_-_Gipfelplateau.JPG/1920px-Geschriebenstein_-_Gipfelplateau.JPG',
    verhaeltnis: 1.700,
    alt: 'Geschriebenstein',
    autor: 'C.Stadler/Bwag',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AGeschriebenstein_-_Gipfelplateau.JPG',
    km: 0.4,
  },
  'graz-altstadt-sehenswuerdigkeiten': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/16-07-06-Rathaus_Graz_Balkon-RR2_0211-0213.jpg/1920px-16-07-06-Rathaus_Graz_Balkon-RR2_0211-0213.jpg',
    verhaeltnis: 1.749,
    alt: 'Graz entdecken',
    autor: 'Ralf Roletschek',
    lizenz: 'CC BY-SA 3.0 at',
    quelle: 'https://commons.wikimedia.org/wiki/File%3A16-07-06-Rathaus_Graz_Balkon-RR2_0211-0213.jpg',
    km: 0.07,
  },
  'grossarltal-tal-der-almen': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Kirche_Gro%C3%9Farl_3569.JPG/1920px-Kirche_Gro%C3%9Farl_3569.JPG',
    verhaeltnis: 1.500,
    alt: 'Großarltal',
    autor: 'Herbert r',
    lizenz: 'CC BY-SA 3.0 at',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AKirche_Gro%C3%9Farl_3569.JPG',
    km: 0.34,
  },
  'grosses-walsertal-biosphaerenpark': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Gro%C3%9Fes_Walsertal_Panorama_2.jpg/1920px-Gro%C3%9Fes_Walsertal_Panorama_2.jpg',
    verhaeltnis: 2.392,
    alt: 'Großes Walsertal',
    autor: 'böhringer friedrich',
    lizenz: 'CC BY-SA 2.5',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AGro%C3%9Fes_Walsertal_Panorama_2.jpg',
    km: 2.84,
  },
  'grossglockner-tagesausflug': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Grossglockner_High_Alpine_Road_%28223587703%29.jpeg',
    verhaeltnis: 1.500,
    alt: 'Großglockner Hochalpenstraße',
    autor: 'Artem Kavalerov',
    lizenz: 'CC0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AGrossglockner_High_Alpine_Road_%28223587703%29.jpeg',
    km: 0.68,
  },
  'gruener-see-tragoess': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Blick_%C3%BCber_den_Gr%C3%BCnen_See_vom_s%C3%BCd%C3%B6stlichen_Bereich_Richtung_Norden.JPG/1920px-Blick_%C3%BCber_den_Gr%C3%BCnen_See_vom_s%C3%BCd%C3%B6stlichen_Bereich_Richtung_Norden.JPG',
    verhaeltnis: 1.505,
    alt: 'gruener-see-tragoess',
    autor: 'Ewood49',
    lizenz: 'CC BY-SA 3.0 at',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ABlick_%C3%BCber_den_Gr%C3%BCnen_See_vom_s%C3%BCd%C3%B6stlichen_Bereich_Richtung_Norden.JPG',
    km: 3.45,
  },
  'grundlsee-steirisches-meer': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Aerial_image_of_Lake_Grundlsee_%28view_from_the_west%29.jpg/1920px-Aerial_image_of_Lake_Grundlsee_%28view_from_the_west%29.jpg',
    verhaeltnis: 1.636,
    alt: 'Grundlsee',
    autor: 'Carsten Steger',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AAerial_image_of_Lake_Grundlsee_%28view_from_the_west%29.jpg',
    km: 2.44,
  },
  'gurker-dom-romanik-kaernten': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Gurker_Dom_S%C3%BCdportal_Tympanon.jpg/1920px-Gurker_Dom_S%C3%BCdportal_Tympanon.jpg',
    verhaeltnis: 1.333,
    alt: 'Gurker Dom',
    autor: 'de:Benutzer:Griensteidl',
    lizenz: 'CC BY-SA 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AGurker_Dom_S%C3%BCdportal_Tympanon.jpg',
    km: 0.41,
  },
  'heiligenblut-grossglockner-dorf': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Gro%C3%9Fglockner_Hochalpenstra%C3%9Fe_21082018_14.jpg/1920px-Gro%C3%9Fglockner_Hochalpenstra%C3%9Fe_21082018_14.jpg',
    verhaeltnis: 1.500,
    alt: 'Heiligenblut am Großglockner',
    autor: 'PantheraLeo1359531',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AGro%C3%9Fglockner_Hochalpenstra%C3%9Fe_21082018_14.jpg',
    km: 0.79,
  },
  'hintertuxer-gletscher': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Hintertuxer_Gletscher%2C_Tux_%28LRM_20260501_131854%29.jpg/1920px-Hintertuxer_Gletscher%2C_Tux_%28LRM_20260501_131854%29.jpg',
    verhaeltnis: 1.336,
    alt: 'Hintertuxer Gletscher',
    autor: 'Matti Blume',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AHintertuxer_Gletscher%2C_Tux_%28LRM_20260501_131854%29.jpg',
    km: 1.26,
  },
  'hochschwab-wandern': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Fleischerbiwak_Hochschwab_im-Nebel_2025-09-26.jpg/1920px-Fleischerbiwak_Hochschwab_im-Nebel_2025-09-26.jpg',
    verhaeltnis: 1.333,
    alt: 'Hochschwab',
    autor: 'h_i_',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AFleischerbiwak_Hochschwab_im-Nebel_2025-09-26.jpg',
    km: 0.67,
  },
  'hundertwasserhaus-kunsthauswien': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Wien_-_Hundertwasserhaus_20180509-12.jpg/1920px-Wien_-_Hundertwasserhaus_20180509-12.jpg',
    verhaeltnis: 1.500,
    alt: 'Hundertwasserhaus & KunstHausWien',
    autor: 'Pymouss',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AWien_-_Hundertwasserhaus_20180509-12.jpg',
    km: 0.1,
  },
  'innsbruck-sehenswuerdigkeiten': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Innsbruck_entre_el_Triumphpforte_y_Adolf-Pichler-Platz_44.jpg/1920px-Innsbruck_entre_el_Triumphpforte_y_Adolf-Pichler-Platz_44.jpg',
    verhaeltnis: 1.500,
    alt: 'Innsbruck',
    autor: 'Álvaro de la Paz Franco',
    lizenz: 'CC0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AInnsbruck_entre_el_Triumphpforte_y_Adolf-Pichler-Platz_44.jpg',
    km: 0.09,
  },
  'karawanken-grenzwanderung-oesterreich-slowenien': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/View_of_the_eastern_extension_of_Kosuta_and_a_hamlet_of_Korte_%28Troegern%29_02.jpg/1920px-View_of_the_eastern_extension_of_Kosuta_and_a_hamlet_of_Korte_%28Troegern%29_02.jpg',
    verhaeltnis: 1.333,
    alt: 'Karawanken-Grenzkamm',
    autor: 'Ajznponar',
    lizenz: 'CC0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AView_of_the_eastern_extension_of_Kosuta_and_a_hamlet_of_Korte_%28Troegern%29_02.jpg',
    km: 2.86,
  },
  'karren-dornbirn': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Karrenberg_Panorama_Rheintal_1.JPG/1920px-Karrenberg_Panorama_Rheintal_1.JPG',
    verhaeltnis: 2.075,
    alt: 'Karren',
    autor: 'Feel free to use my photos, but please mention me as the author and if',
    lizenz: 'CC BY-SA 3.0 at',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AKarrenberg_Panorama_Rheintal_1.JPG',
    km: 0.01,
  },
  'keutschacher-seental-radtour': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Keutschacher_See_23092013_566.jpg/1920px-Keutschacher_See_23092013_566.jpg',
    verhaeltnis: 1.509,
    alt: 'Keutschacher Seental',
    autor: 'Johann Jaritz',
    lizenz: 'CC BY-SA 3.0 at',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AKeutschacher_See_23092013_566.jpg',
    km: 2.66,
  },
  'kittsee-schloss': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Kittsee_castle_-_panoramio_-_bredus_%281%29.jpg/1920px-Kittsee_castle_-_panoramio_-_bredus_%281%29.jpg',
    verhaeltnis: 1.333,
    alt: 'Kittsee',
    autor: 'bredus',
    lizenz: 'CC BY 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AKittsee_castle_-_panoramio_-_bredus_%281%29.jpg',
    km: 0.57,
  },
  'kitzbuehel-ausflug': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Kitzb%C3%BCheler_Altstadt_%2826985186771%29.jpg/1920px-Kitzb%C3%BCheler_Altstadt_%2826985186771%29.jpg',
    verhaeltnis: 1.333,
    alt: 'Kitzbühel',
    autor: 'Ștefan Jurcă from Munich, Germany',
    lizenz: 'CC BY 2.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AKitzb%C3%BCheler_Altstadt_%2826985186771%29.jpg',
    km: 0.06,
  },
  'kitzsteinhorn-kaprun': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/AUT_%E2%80%94_Land_Salzburg_%E2%80%94_Bezirk_Zell_am_See_%E2%80%94_Gemeinde_Kaprun_%E2%80%94_Gipfelbahn_Kitzsteinhorn_%28Bergstation_Gondelabfertigung_Talfahrt%29_2021.jpg/1920px-AUT_%E2%80%94_Land_Salzburg_%E2%80%94_Bezirk_Zell_am_See_%E2%80%94_Gemeinde_Kaprun_%E2%80%94_Gipfelbahn_Kitzsteinhorn_%28Bergstation_Gondelabfertigung_Talfahrt%29_2021.jpg',
    verhaeltnis: 1.333,
    alt: 'Kitzsteinhorn Kaprun',
    autor: 'User:Mateus2019',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AAUT_%E2%80%94_Land_Salzburg_%E2%80%94_Bezirk_Zell_am_See_%E2%80%94_Gemeinde_Kaprun_%E2%80%94_Gipfelbahn_Kitzsteinhorn_%28Bergstation_Gondelabfertigung_Talfahrt%29_2021.jpg',
    km: 0.37,
  },
  'klagenfurt-stadtfuehrung': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/St._Egid%27s_Bell_Tower_-_Klagenfurt_am_W%C3%B6rthersee%2C_Carinthia%2C_Austria_-_July_4%2C_2025_02.jpg/1920px-St._Egid%27s_Bell_Tower_-_Klagenfurt_am_W%C3%B6rthersee%2C_Carinthia%2C_Austria_-_July_4%2C_2025_02.jpg',
    verhaeltnis: 1.500,
    alt: 'Klagenfurt entdecken',
    autor: 'Giorgio Galeotti',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ASt._Egid%27s_Bell_Tower_-_Klagenfurt_am_W%C3%B6rthersee%2C_Carinthia%2C_Austria_-_July_4%2C_2025_02.jpg',
    km: 0.16,
  },
  'kleinwalsertal-wandern': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Kleinwalsertal-widderstein%2Bwalmedinger_horn01.jpg/1920px-Kleinwalsertal-widderstein%2Bwalmedinger_horn01.jpg',
    verhaeltnis: 1.349,
    alt: 'Kleinwalsertal',
    autor: 'Nikater',
    lizenz: 'Public domain',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AKleinwalsertal-widderstein%2Bwalmedinger_horn01.jpg',
    km: 0.13,
  },
  'klopeiner-see-badeurlaub': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Sankt_Kanzian_Klopeiner_See_vom_Georgiberg_gesehen_06122007_02.jpg/1920px-Sankt_Kanzian_Klopeiner_See_vom_Georgiberg_gesehen_06122007_02.jpg',
    verhaeltnis: 1.494,
    alt: 'Klopeiner See',
    autor: 'Johann Jaritz',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ASankt_Kanzian_Klopeiner_See_vom_Georgiberg_gesehen_06122007_02.jpg',
    km: 2.26,
  },
  'lainzer-tiergarten-wien': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Lainzer_Tiergarten_Waldweg_zum_Wiener_Blick_1.jpg/1920px-Lainzer_Tiergarten_Waldweg_zum_Wiener_Blick_1.jpg',
    verhaeltnis: 1.500,
    alt: 'Lainzer Tiergarten',
    autor: 'styko',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ALainzer_Tiergarten_Waldweg_zum_Wiener_Blick_1.jpg',
    km: 0.45,
  },
  'lech-zuers-am-arlberg': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Lech-Tannberg-Lech_%28river%29-Omesberg-Lech_%28centre%29-Schraegluftbild_Raumplanung_Vorarlberg_%28343129%29.jpg/1920px-Lech-Tannberg-Lech_%28river%29-Omesberg-Lech_%28centre%29-Schraegluftbild_Raumplanung_Vorarlberg_%28343129%29.jpg',
    verhaeltnis: 1.537,
    alt: 'Lech-Zürs am Arlberg',
    autor: 'Raumplanung Vorarlberg, Amt der Vorarlberger Landesregierung (pid vola',
    lizenz: 'CC BY 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ALech-Tannberg-Lech_%28river%29-Omesberg-Lech_%28centre%29-Schraegluftbild_Raumplanung_Vorarlberg_%28343129%29.jpg',
    km: 0.3,
  },
  'liechtensteinklamm': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Aerial_image_of_the_Tennen_Mountains_%28view_from_the_south%29.jpg/1920px-Aerial_image_of_the_Tennen_Mountains_%28view_from_the_south%29.jpg',
    verhaeltnis: 1.618,
    alt: 'Liechtensteinklamm',
    autor: 'Carsten Steger',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AAerial_image_of_the_Tennen_Mountains_%28view_from_the_south%29.jpg',
    km: 2.04,
  },
  'linz-ausflug': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Linz-Hauptplatz-Dreifaltigkeitss%C3%A4ule-05400.jpg/1920px-Linz-Hauptplatz-Dreifaltigkeitss%C3%A4ule-05400.jpg',
    verhaeltnis: 1.500,
    alt: 'Linz',
    autor: 'Rainer Halama',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ALinz-Hauptplatz-Dreifaltigkeitss%C3%A4ule-05400.jpg',
    km: 0.01,
  },
  'lunzer-see-baden': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Lunzer_See_2022-08-07_16.jpg/1920px-Lunzer_See_2022-08-07_16.jpg',
    verhaeltnis: 1.494,
    alt: 'Lunzer See',
    autor: 'Leonhard Lenz',
    lizenz: 'CC0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ALunzer_See_2022-08-07_16.jpg',
    km: 1.05,
  },
  'lurgrotte-tropfsteinhoehle-steiermark': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Zbytek_ledop%C3%A1du_u_vstupu_do_jeskyn%C4%9B_Lurgrotte.jpg/1920px-Zbytek_ledop%C3%A1du_u_vstupu_do_jeskyn%C4%9B_Lurgrotte.jpg',
    verhaeltnis: 1.333,
    alt: 'Lurgrotte',
    autor: 'Ladabohac',
    lizenz: 'CC0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AZbytek_ledop%C3%A1du_u_vstupu_do_jeskyn%C4%9B_Lurgrotte.jpg',
    km: 3.0,
  },
  'millstaetter-see-wandern-und-schwimmen': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Millstatt_Steingew%C3%B6lbebr%C3%BCcke_Obermillst%C3%A4tter_Stra%C3%9Fe_2014.jpg/1920px-Millstatt_Steingew%C3%B6lbebr%C3%BCcke_Obermillst%C3%A4tter_Stra%C3%9Fe_2014.jpg',
    verhaeltnis: 1.500,
    alt: 'Millstätter See',
    autor: 'Joadl',
    lizenz: 'CC BY-SA 3.0 at',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AMillstatt_Steingew%C3%B6lbebr%C3%BCcke_Obermillst%C3%A4tter_Stra%C3%9Fe_2014.jpg',
    km: 0.39,
  },
  'moerbisch-seefestspiele': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Lake_Neusiedl%2C_M%C3%B6rbisch_am_See%2C_Austria%2C_20220425_1531_5294.jpg/1920px-Lake_Neusiedl%2C_M%C3%B6rbisch_am_See%2C_Austria%2C_20220425_1531_5294.jpg',
    verhaeltnis: 1.498,
    alt: 'Mörbisch & die Seefestspiele',
    autor: 'Jakub Hałun',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ALake_Neusiedl%2C_M%C3%B6rbisch_am_See%2C_Austria%2C_20220425_1531_5294.jpg',
    km: 1.56,
  },
  'mondsee-baden-salzkammergut': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Aerial_image_of_Mondsee_Abbey_%28view_from_the_southwest%29.jpg/1920px-Aerial_image_of_Mondsee_Abbey_%28view_from_the_southwest%29.jpg',
    verhaeltnis: 1.500,
    alt: 'Mondsee',
    autor: 'Carsten Steger',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AAerial_image_of_Mondsee_Abbey_%28view_from_the_southwest%29.jpg',
    km: 0.53,
  },
  'murradweg-steiermark': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Murau_-_Schloss_%28b%29.JPG/1920px-Murau_-_Schloss_%28b%29.JPG',
    verhaeltnis: 1.500,
    alt: 'Murradweg',
    autor: 'C.Stadler/Bwag',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AMurau_-_Schloss_%28b%29.JPG',
    km: 0.11,
  },
  'museumsquartier-wien': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/MuseumsQuartier_Vienna_-_A_Day_in_the_Cultural_Heart_of_Austria.jpg/1920px-MuseumsQuartier_Vienna_-_A_Day_in_the_Cultural_Heart_of_Austria.jpg',
    verhaeltnis: 1.500,
    alt: 'MuseumsQuartier',
    autor: 'Sandor Somkuti',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AMuseumsQuartier_Vienna_-_A_Day_in_the_Cultural_Heart_of_Austria.jpg',
    km: 0.01,
  },
  'nationalpark-thayatal-hardegg': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Hardegg_-_Burg_%283%29.JPG/1920px-Hardegg_-_Burg_%283%29.JPG',
    verhaeltnis: 1.778,
    alt: 'Nationalpark Thayatal',
    autor: 'C.Stadler/Bwag (talk / email)',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AHardegg_-_Burg_%283%29.JPG',
    km: 2.46,
  },
  'nockberge-biosphaerenpark-wandern': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Nationalpark_Nockberge_Landschaft_26082007_01.jpg/1920px-Nationalpark_Nockberge_Landschaft_26082007_01.jpg',
    verhaeltnis: 1.494,
    alt: 'Nockberge',
    autor: 'Johann Jaritz',
    lizenz: 'CC BY-SA 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ANationalpark_Nockberge_Landschaft_26082007_01.jpg',
    km: 1.69,
  },
  'oetztal-soelden': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/S%C3%B6lden_-_view_5.jpg/1920px-S%C3%B6lden_-_view_5.jpg',
    verhaeltnis: 1.522,
    alt: 'Ötztal & Sölden',
    autor: 'Tiia Monto',
    lizenz: 'CC BY-SA 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AS%C3%B6lden_-_view_5.jpg',
    km: 0.58,
  },
  'ossiacher-see-badeurlaub': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/2014-06-26_Ossiacher_See_-_Unwetter_-hu-_1919.jpg/1920px-2014-06-26_Ossiacher_See_-_Unwetter_-hu-_1919.jpg',
    verhaeltnis: 1.500,
    alt: 'Ossiacher See',
    autor: 'Hubertl',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3A2014-06-26_Ossiacher_See_-_Unwetter_-hu-_1919.jpg',
    km: 0.3,
  },
  'plansee-tirol-baden': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Aerial_image_of_Plansee_%28view_from_the_east%29.jpg/1920px-Aerial_image_of_Plansee_%28view_from_the_east%29.jpg',
    verhaeltnis: 1.547,
    alt: 'Plansee & Heiterwanger See',
    autor: 'Carsten Steger',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AAerial_image_of_Plansee_%28view_from_the_east%29.jpg',
    km: 2.53,
  },
  'poellauer-tal-naturpark': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/P%C3%B6llauer_Safen.JPG/1920px-P%C3%B6llauer_Safen.JPG',
    verhaeltnis: 1.504,
    alt: 'Naturpark Pöllauer Tal',
    autor: 'Herzi Pinki',
    lizenz: 'CC BY-SA 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AP%C3%B6llauer_Safen.JPG',
    km: 0.34,
  },
  'rax-seilbahn': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Reichenau_-_Wolfgang-Dirnbacher-H%C3%BCtte.JPG/1920px-Reichenau_-_Wolfgang-Dirnbacher-H%C3%BCtte.JPG',
    verhaeltnis: 1.500,
    alt: 'Rax',
    autor: 'C.Stadler/Bwag',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AReichenau_-_Wolfgang-Dirnbacher-H%C3%BCtte.JPG',
    km: 0.29,
  },
  'reschensee-versunkener-kirchturm': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Reschensee_with_Graun_Church_tower_and_boat.jpg/1920px-Reschensee_with_Graun_Church_tower_and_boat.jpg',
    verhaeltnis: 1.778,
    alt: 'Reschensee',
    autor: 'Noclador',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AReschensee_with_Graun_Church_tower_and_boat.jpg',
    km: 0.18,
  },
  'ried-im-innkreis-antiesental': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Hauptplatz_Ried_im_Innkreis_01.jpg/1920px-Hauptplatz_Ried_im_Innkreis_01.jpg',
    verhaeltnis: 1.778,
    alt: 'Ried im Innkreis & Antiesental',
    autor: 'H.Helmlechner',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AHauptplatz_Ried_im_Innkreis_01.jpg',
    km: 0.28,
  },
  'riegersburg-burg-ausflug': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Riegersburg-Castle-04ASD.jpg/1920px-Riegersburg-Castle-04ASD.jpg',
    verhaeltnis: 1.778,
    alt: 'Riegersburg',
    autor: 'Asurnipal',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ARiegersburg-Castle-04ASD.jpg',
    km: 0.22,
  },
  'roemersteinbruch-st-margarethen-oper': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Sankt_Margarethen_im_Burgenland%2C_Blick_nach_S%C3%BCden.jpg/1920px-Sankt_Margarethen_im_Burgenland%2C_Blick_nach_S%C3%BCden.jpg',
    verhaeltnis: 1.628,
    alt: 'Römersteinbruch St. Margarethen',
    autor: 'Dguendel',
    lizenz: 'CC BY 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ASankt_Margarethen_im_Burgenland%2C_Blick_nach_S%C3%BCden.jpg',
    km: 1.65,
  },
  'rust-stoerche-altstadt': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Katholische_Pfarrkirche_Rust_am_See_07.jpg/1920px-Katholische_Pfarrkirche_Rust_am_See_07.jpg',
    verhaeltnis: 1.501,
    alt: 'Rust am Neusiedler See',
    autor: 'Helmlechner',
    lizenz: 'CC0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AKatholische_Pfarrkirche_Rust_am_See_07.jpg',
    km: 0.35,
  },
  'saalbach-hinterglemm': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/AUT_%E2%80%94_Bundesland_Salzburg_%E2%80%94_Bezirk_Zell_am_See_%E2%80%94_Gem._Saalbach-Hinterglemm_%E2%80%94_Saalbach_%28Strassentunnel_unter_der_Kohlmaisbahn%29_2021.jpg/1920px-AUT_%E2%80%94_Bundesland_Salzburg_%E2%80%94_Bezirk_Zell_am_See_%E2%80%94_Gem._Saalbach-Hinterglemm_%E2%80%94_Saalbach_%28Strassentunnel_unter_der_Kohlmaisbahn%29_2021.jpg',
    verhaeltnis: 1.333,
    alt: 'Saalbach-Hinterglemm',
    autor: 'Mateus2019',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AAUT_%E2%80%94_Bundesland_Salzburg_%E2%80%94_Bezirk_Zell_am_See_%E2%80%94_Gem._Saalbach-Hinterglemm_%E2%80%94_Saalbach_%28Strassentunnel_unter_der_Kohlmaisbahn%29_2021.jpg',
    km: 0.68,
  },
  'salzburger-seenland-baden': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Strandbad_Mattsee_6249.jpg/1920px-Strandbad_Mattsee_6249.jpg',
    verhaeltnis: 1.500,
    alt: 'Salzburger Seenland',
    autor: 'Henry Kellner',
    lizenz: 'CC BY-SA 3.0 at',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AStrandbad_Mattsee_6249.jpg',
    km: 0.29,
  },
  'salzwelten-hallein-duerrnberg': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/20190129_Salzwelten_9474_%2847332285112%29.jpg/1920px-20190129_Salzwelten_9474_%2847332285112%29.jpg',
    verhaeltnis: 1.500,
    alt: 'Salzwelten Hallein',
    autor: 'Ray Swi-hymn from Sijhih-Taipei, Taiwan',
    lizenz: 'CC BY-SA 2.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3A20190129_Salzwelten_9474_%2847332285112%29.jpg',
    km: 1.02,
  },
  'schaerding-altstadt-innviertel': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Sch%C3%A4rding%2C_Blick_zur_neuen_Innbr%C3%BCcke.jpg/1920px-Sch%C3%A4rding%2C_Blick_zur_neuen_Innbr%C3%BCcke.jpg',
    verhaeltnis: 1.500,
    alt: 'Schärding',
    autor: 'Dguendel',
    lizenz: 'CC BY 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ASch%C3%A4rding%2C_Blick_zur_neuen_Innbr%C3%BCcke.jpg',
    km: 0.86,
  },
  'schladming-dachstein-wandern': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/View_over_Schladming%2C_February_2013_-_panoramio.jpg/1920px-View_over_Schladming%2C_February_2013_-_panoramio.jpg',
    verhaeltnis: 1.333,
    alt: 'Wandern in Schladming-Dachstein',
    autor: 'Stör95',
    lizenz: 'CC BY 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AView_over_Schladming%2C_February_2013_-_panoramio.jpg',
    km: 0.99,
  },
  'schloegener-schlinge-donau': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Aerial_image_of_Schl%C3%B6gener_Schlinge_%28view_from_the_southeast%29.jpg/1920px-Aerial_image_of_Schl%C3%B6gener_Schlinge_%28view_from_the_southeast%29.jpg',
    verhaeltnis: 1.636,
    alt: 'Schlögener Schlinge',
    autor: 'Carsten Steger',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AAerial_image_of_Schl%C3%B6gener_Schlinge_%28view_from_the_southeast%29.jpg',
    km: 1.63,
  },
  'schloss-belvedere-wien': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Schloss_Belvedere_von_Johann_Lucas_von_Hildebrandt_f%C3%BCr_Prinz_Eugen_von_Savoyen_erbaut_-_panoramio.jpg/1920px-Schloss_Belvedere_von_Johann_Lucas_von_Hildebrandt_f%C3%BCr_Prinz_Eugen_von_Savoyen_erbaut_-_panoramio.jpg',
    verhaeltnis: 1.500,
    alt: 'Schloss Belvedere',
    autor: 'Martin Furtschegger',
    lizenz: 'CC BY 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ASchloss_Belvedere_von_Johann_Lucas_von_Hildebrandt_f%C3%BCr_Prinz_Eugen_von_Savoyen_erbaut_-_panoramio.jpg',
    km: 0.02,
  },
  'schloss-grafenegg-kamptal': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/GuentherZ_2014-05-01_%2830%29_Schloss_Grafenegg.JPG/1920px-GuentherZ_2014-05-01_%2830%29_Schloss_Grafenegg.JPG',
    verhaeltnis: 1.500,
    alt: 'Schloss Grafenegg',
    autor: 'GuentherZ',
    lizenz: 'CC BY-SA 3.0 at',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AGuentherZ_2014-05-01_%2830%29_Schloss_Grafenegg.JPG',
    km: 2.83,
  },
  'schloss-halbturn': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Schloss_Halbturn_1098.jpg/1920px-Schloss_Halbturn_1098.jpg',
    verhaeltnis: 1.778,
    alt: 'Schloss Halbturn',
    autor: 'Henry Kellner',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ASchloss_Halbturn_1098.jpg',
    km: 0.4,
  },
  'schoeckl-graz-hausberg': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/3/30/View_from_Sch%C3%B6ckl_-_panoramio.jpg',
    verhaeltnis: 1.778,
    alt: 'Schöckl',
    autor: 'battabikee',
    lizenz: 'CC BY 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AView_from_Sch%C3%B6ckl_-_panoramio.jpg',
    km: 1.35,
  },
  'seefeld-tirol': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/AUT_%E2%80%93_Tirol_%E2%80%93_Bezirk_Innsbruck-Land_%E2%80%94_Gemeinde_Seefeld_in_Tirol_%E2%80%94_Seefeld_in_Tirol_Dorf_%28Kurpark%29_2023-07-08_Mattes.jpg/1920px-AUT_%E2%80%93_Tirol_%E2%80%93_Bezirk_Innsbruck-Land_%E2%80%94_Gemeinde_Seefeld_in_Tirol_%E2%80%94_Seefeld_in_Tirol_Dorf_%28Kurpark%29_2023-07-08_Mattes.jpg',
    verhaeltnis: 2.162,
    alt: 'Seefeld in Tirol',
    autor: 'User:Mateus2019',
    lizenz: 'CC BY 3.0 de',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AAUT_%E2%80%93_Tirol_%E2%80%93_Bezirk_Innsbruck-Land_%E2%80%94_Gemeinde_Seefeld_in_Tirol_%E2%80%94_Seefeld_in_Tirol_Dorf_%28Kurpark%29_2023-07-08_Mattes.jpg',
    km: 0.19,
  },
  'st-anton-am-arlberg': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Park_n%C3%A4chst_dem_Hannes-Schneider-Weg%2C_St._Anton_am_Arlberg%2C_23.02.2019.jpg/1920px-Park_n%C3%A4chst_dem_Hannes-Schneider-Weg%2C_St._Anton_am_Arlberg%2C_23.02.2019.jpg',
    verhaeltnis: 1.500,
    alt: 'St. Anton am Arlberg',
    autor: 'Liberaler Humanist',
    lizenz: 'CC BY-SA 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3APark_n%C3%A4chst_dem_Hannes-Schneider-Weg%2C_St._Anton_am_Arlberg%2C_23.02.2019.jpg',
    km: 0.39,
  },
  'stausee-ottenstein-waldviertel': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Zwettl_-_Stausee_Ottenstein.JPG/1920px-Zwettl_-_Stausee_Ottenstein.JPG',
    verhaeltnis: 1.780,
    alt: 'Stausee Ottenstein',
    autor: 'C.Stadler/Bwag',
    lizenz: 'CC BY 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AZwettl_-_Stausee_Ottenstein.JPG',
    km: 1.01,
  },
  'steirisches-vulkanland': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Feldbach_-_Zentrum_mit_Villa_Hold_und_Kirche.JPG/1920px-Feldbach_-_Zentrum_mit_Villa_Hold_und_Kirche.JPG',
    verhaeltnis: 1.638,
    alt: 'Steirisches Vulkanland',
    autor: 'C.Stadler/Bwag',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AFeldbach_-_Zentrum_mit_Villa_Hold_und_Kirche.JPG',
    km: 0.96,
  },
  'steppentierpark-pamhagen': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Pamhagen_-_Kirche_%281%29.JPG/1920px-Pamhagen_-_Kirche_%281%29.JPG',
    verhaeltnis: 1.500,
    alt: 'Steppentierpark Pamhagen',
    autor: 'C.Stadler/Bwag',
    lizenz: 'CC BY-SA 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3APamhagen_-_Kirche_%281%29.JPG',
    km: 1.7,
  },
  'stift-admont-bibliothek': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Stift_Admont_Pavillon_20211223.jpg/1920px-Stift_Admont_Pavillon_20211223.jpg',
    verhaeltnis: 1.665,
    alt: 'Stift Admont',
    autor: 'Daniel Kraft',
    lizenz: 'CC BY-SA 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AStift_Admont_Pavillon_20211223.jpg',
    km: 0.23,
  },
  'stift-melk': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/20231227.Stift_Melk.-017.jpg/1920px-20231227.Stift_Melk.-017.jpg',
    verhaeltnis: 1.649,
    alt: 'Stift Melk',
    autor: 'Bybbisch94',
    lizenz: 'CC BY 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3A20231227.Stift_Melk.-017.jpg',
    km: 0.04,
  },
  'stubaital-stubaier-gletscher': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Neustift_im_Stubaital%2C_view_on_peak_Serles_%28%5E%29_2718_m_-_panoramio.jpg/1920px-Neustift_im_Stubaital%2C_view_on_peak_Serles_%28%5E%29_2718_m_-_panoramio.jpg',
    verhaeltnis: 1.500,
    alt: 'Stubaital & Stubaier Gletscher',
    autor: 'Wojciech Biegun',
    lizenz: 'CC BY-SA 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ANeustift_im_Stubaital%2C_view_on_peak_Serles_%28%5E%29_2718_m_-_panoramio.jpg',
    km: 1.12,
  },
  'therme-loipersdorf-steiermark': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Loipersdorf_Thermen_50390.jpg/1920px-Loipersdorf_Thermen_50390.jpg',
    verhaeltnis: 1.818,
    alt: 'Thermen in der Steiermark',
    autor: 'Jacquesverlaeken',
    lizenz: 'CC BY-SA 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ALoipersdorf_Thermen_50390.jpg',
    km: 0.9,
  },
  'traunsee-gmunden': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/2018-08-25_AT_Gmunden%2C_Esplanade%2C_Franz-Josef-Platz%2C_GM_100%2C_GM_5%2C_GM_8%2C_GM_9%2C_GM_10_%2850691907943%29.jpg/1920px-2018-08-25_AT_Gmunden%2C_Esplanade%2C_Franz-Josef-Platz%2C_GM_100%2C_GM_5%2C_GM_8%2C_GM_9%2C_GM_10_%2850691907943%29.jpg',
    verhaeltnis: 1.495,
    alt: 'Traunsee & Gmunden',
    autor: 'Paul Korecky',
    lizenz: 'CC BY-SA 2.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3A2018-08-25_AT_Gmunden%2C_Esplanade%2C_Franz-Josef-Platz%2C_GM_100%2C_GM_5%2C_GM_8%2C_GM_9%2C_GM_10_%2850691907943%29.jpg',
    km: 0.12,
  },
  'untersberg-salzburg': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Untersberg_in_winter_of_2023-25.jpg/1920px-Untersberg_in_winter_of_2023-25.jpg',
    verhaeltnis: 1.776,
    alt: 'Untersberg',
    autor: 'Renek78',
    lizenz: 'CC0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AUntersberg_in_winter_of_2023-25.jpg',
    km: 0.44,
  },
  'velden-am-woerthersee-urlaub': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/W%C3%B6rthersee_-_Velden_am_W%C3%B6rther_See%2C_Villach-Land%2C_Carinthia%2C_Austria_-_July_4%2C_2025.jpg/1920px-W%C3%B6rthersee_-_Velden_am_W%C3%B6rther_See%2C_Villach-Land%2C_Carinthia%2C_Austria_-_July_4%2C_2025.jpg',
    verhaeltnis: 1.500,
    alt: 'Velden am Wörthersee',
    autor: 'Giorgio Galeotti',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AW%C3%B6rthersee_-_Velden_am_W%C3%B6rther_See%2C_Villach-Land%2C_Carinthia%2C_Austria_-_July_4%2C_2025.jpg',
    km: 0.42,
  },
  'wachau-duernstein': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/D%C3%BCrnstein_Ruine-7382.jpg/1920px-D%C3%BCrnstein_Ruine-7382.jpg',
    verhaeltnis: 1.500,
    alt: 'Wachau & Dürnstein',
    autor: 'Isiwal',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AD%C3%BCrnstein_Ruine-7382.jpg',
    km: 0.08,
  },
  'weissensee-kaernten-geheimtipp': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Wei%C3%9Fensee_-_Wiese_am_S%C3%BCdufer.JPG/1920px-Wei%C3%9Fensee_-_Wiese_am_S%C3%BCdufer.JPG',
    verhaeltnis: 1.500,
    alt: 'Weissensee',
    autor: 'Mefusbren69',
    lizenz: 'Public domain',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AWei%C3%9Fensee_-_Wiese_am_S%C3%BCdufer.JPG',
    km: 0.86,
  },
  'weissensee-winter-schlittschuhlaufen': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Aussichtsplattform_Wei%C3%9Fensee-04-Panorama.jpg/1920px-Aussichtsplattform_Wei%C3%9Fensee-04-Panorama.jpg',
    verhaeltnis: 2.524,
    alt: 'Weissensee im Winter',
    autor: 'Muck',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AAussichtsplattform_Wei%C3%9Fensee-04-Panorama.jpg',
    km: 1.97,
  },
  'wien-schoenbrunn': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Schlo%C3%9F_Sch%C3%B6nbrunn_Wien%2C_Parkseite_2.JPG/1920px-Schlo%C3%9F_Sch%C3%B6nbrunn_Wien%2C_Parkseite_2.JPG',
    verhaeltnis: 1.500,
    alt: 'Schloss Schönbrunn',
    autor: 'Feel free to use my photos, but please mention me as the author and if',
    lizenz: 'CC BY-SA 3.0 at',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ASchlo%C3%9F_Sch%C3%B6nbrunn_Wien%2C_Parkseite_2.JPG',
    km: 0.04,
  },
  'wien-stephansdom-altstadt': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Wien%2C_Stephansdom%2C_Blick_vom_S%C3%BCdturm_--_2018_--_3268.jpg/1920px-Wien%2C_Stephansdom%2C_Blick_vom_S%C3%BCdturm_--_2018_--_3268.jpg',
    verhaeltnis: 1.500,
    alt: 'Stephansdom & Altstadt',
    autor: 'Dietmar Rabich',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AWien%2C_Stephansdom%2C_Blick_vom_S%C3%BCdturm_--_2018_--_3268.jpg',
    km: 0.0,
  },
  'wienerwald-wandern': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Wien_view_from_Kahlenberg_-_panoramio.jpg/1920px-Wien_view_from_Kahlenberg_-_panoramio.jpg',
    verhaeltnis: 1.509,
    alt: 'Wienerwald',
    autor: 'Alireza Javaheri',
    lizenz: 'CC BY 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AWien_view_from_Kahlenberg_-_panoramio.jpg',
    km: 0.23,
  },
  'wilder-kaiser-wandern': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Sonnenuntergang_am_Kaisergebirge%2C_Tirol%2C_160623%2C_ako.jpg/1920px-Sonnenuntergang_am_Kaisergebirge%2C_Tirol%2C_160623%2C_ako.jpg',
    verhaeltnis: 1.500,
    alt: 'Wilder Kaiser',
    autor: 'Ansgar Koreng',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ASonnenuntergang_am_Kaisergebirge%2C_Tirol%2C_160623%2C_ako.jpg',
    km: 2.39,
  },
  'woerthersee-mit-kindern': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/9210_P%C3%B6rtschach_am_W%C3%B6rther_See%2C_W%C3%B6rthersee_01_2023-08-23.jpg/1920px-9210_P%C3%B6rtschach_am_W%C3%B6rther_See%2C_W%C3%B6rthersee_01_2023-08-23.jpg',
    verhaeltnis: 1.537,
    alt: 'Wörthersee mit Kindern',
    autor: 'Hangman\'sDeath',
    lizenz: 'CC0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3A9210_P%C3%B6rtschach_am_W%C3%B6rther_See%2C_W%C3%B6rthersee_01_2023-08-23.jpg',
    km: 0.99,
  },
  'woerthersee-radweg-komplett': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/W%C3%B6rthersee%2CMaria_W%C3%B6rth._-_panoramio.jpg/1920px-W%C3%B6rthersee%2CMaria_W%C3%B6rth._-_panoramio.jpg',
    verhaeltnis: 1.780,
    alt: 'Wörthersee Radweg',
    autor: 'nnike',
    lizenz: 'CC BY 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AW%C3%B6rthersee%2CMaria_W%C3%B6rth._-_panoramio.jpg',
    km: 1.27,
  },
  'woerthersee-schifffahrt': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Kapuzinerinsel_im_W%C3%B6rthersee.JPG/1920px-Kapuzinerinsel_im_W%C3%B6rthersee.JPG',
    verhaeltnis: 1.500,
    alt: 'Schifffahrt am Wörthersee',
    autor: 'JJ55',
    lizenz: 'CC BY-SA 3.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AKapuzinerinsel_im_W%C3%B6rthersee.JPG',
    km: 0.54,
  },
  'wolfgangsee-st-gilgen': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Sankt_gilgen_kirche.jpg/1920px-Sankt_gilgen_kirche.jpg',
    verhaeltnis: 1.500,
    alt: 'Wolfgangsee & St. Gilgen',
    autor: 'Arne Müseler',
    lizenz: 'CC BY-SA 3.0 de',
    quelle: 'https://commons.wikimedia.org/wiki/File%3ASankt_gilgen_kirche.jpg',
    km: 0.42,
  },
  'zillertal-wandern': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Zillertal_in_Tyrol%2C_Austria-panorama_PNr%C2%B00746a.jpg/1920px-Zillertal_in_Tyrol%2C_Austria-panorama_PNr%C2%B00746a.jpg',
    verhaeltnis: 1.603,
    alt: 'Zillertal',
    autor: 'D-Kuru',
    lizenz: 'CC BY-SA 4.0',
    quelle: 'https://commons.wikimedia.org/wiki/File%3AZillertal_in_Tyrol%2C_Austria-panorama_PNr%C2%B00746a.jpg',
    km: 1.63,
  },
};

/** Foto zu einem Artikel – oder undefined, wenn keins geprüft vorliegt. */
export function bildFuer(slug: string): PostBild | undefined {
  return POST_BILDER[slug];
}
